### ISSUE TITLE
Output the Perl sub in Perl files only

### ISSUE THREAD

**Issue by tukusejssirs** [semuel/Sublime-Text-Perl-Subs#3]
I’ve read somewhere that you (@semuel) don’t use and update this repo anymore, but could you at least point me to the direction how to fix this issue.

The Perl subs are output in status bar in all files, not only in Perl files. In non-Perl files, the status bar contains `[PerlSub: <none>]`, which bothers me as it is useless, e.g. in BASH scripts.

**Comment by semuel** [comment]
Indeed. I wrote this plugin 9 years ago, and not using ST or Perl for 6 years already. 
The whole plugin is one file, perlidx.py that is in the root of this repository. 
if you are bothered with the PerlSubs none, you can add an IsPerl call to DisplayCurrentSub.

**Comment by tukusejssirs** [comment]
Thanks, @semuel, for your comment!
